# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:10.16.0

clone: # Doing a full clone to be able to push back to Heroku.
  depth: full

pipelines:
  branches: # When code is pushed to the master branch
    master:
      - step:
          name: Build and test
          caches:
            - node
          script: # Modify the commands below to build your repository.
            - npm install
          # artifacts:
            # - test-reports/**
      - step:
          name: Deploy to Heroku Stage
          script:
            - git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_PROD.git master
